[package]
authors = [
  "Jorge Aparicio <jorge@japaric.io>",
  "Per Lindgren <per.lindgren@ltu.se>",
]
categories = ["concurrency", "embedded", "no-std"]
description = "Real Time For the Masses (RTFM) framework for ARM Cortex-M microcontrollers"
documentation = "https://docs.rs/cortex-m-rtfm"
keywords = ["arm", "cortex-m"]
license = "MIT OR Apache-2.0"
name = "cortex-m-rtfm"
repository = "https://github.com/japaric/cortex-m-rtfm"
version = "0.3.2"

[[example]]
name = "async-after"
required-features = ["timer-queue"]

[[example]]
name = "async"

[[example]]
name = "empty"

[[example]]
name = "interrupt"

[[example]]
name = "interrupt-async"
required-features = ["timer-queue"]

[[example]]
name = "interrupt-async-after"
required-features = ["timer-queue"]

[[example]]
name = "periodic-payload"
required-features = ["timer-queue"]

[[example]]
name = "periodic-preemption-payload"
required-features = ["timer-queue"]

[[example]]
name = "periodic-preemption"
required-features = ["timer-queue"]

[[example]]
name = "periodic"
required-features = ["timer-queue"]

[[example]]
name = "user-struct"
required-features = ["timer-queue"]

[dependencies]
cortex-m = "0.4.0"
cortex-m-rtfm-macros = { path = "macros", version = "0.3.1" }
heapless = "0.3.6"
typenum = "1.10.0"

[target.'cfg(target_arch = "x86_64")'.dev-dependencies]
compiletest_rs = "0.3.5"

[dev-dependencies]
panic-abort = "0.1.1"
panic-itm = "0.1.0"
typenum = "1.10.0"

[dev-dependencies.stm32f103xx]
features = ["rt"]
version = "0.9.0"

[features]
cm7-r0p1 = ["cortex-m/cm7-r0p1"]
timer-queue = ["cortex-m-rtfm-macros/timer-queue"]

[profile.release]
lto = true
codegen-units = 1
